WARNING 2018-11-15 16:22:51,987 base 152 Not Found: /
WARNING 2018-11-15 16:22:51,989 basehttp 124 "GET / HTTP/1.1" 404 2104
WARNING 2018-11-15 16:22:52,973 base 152 Not Found: /favicon.ico
WARNING 2018-11-15 16:22:52,974 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2155
WARNING 2018-11-15 16:23:23,574 base 152 Not Found: /sms_codes
WARNING 2018-11-15 16:23:23,577 basehttp 124 "GET /sms_codes HTTP/1.1" 404 2149
INFO 2018-11-15 16:25:04,457 basehttp 124 "GET /sms_codes/15812341234 HTTP/1.1" 301 0
WARNING 2018-11-15 16:26:55,828 base 152 Not Found: /sms_codes
WARNING 2018-11-15 16:26:55,831 basehttp 124 "GET /sms_codes HTTP/1.1" 404 2149
WARNING 2018-11-15 16:26:56,877 base 152 Not Found: /sms_codes
WARNING 2018-11-15 16:26:56,878 basehttp 124 "GET /sms_codes HTTP/1.1" 404 2149
WARNING 2018-11-15 16:26:57,696 base 152 Not Found: /sms_codes
WARNING 2018-11-15 16:26:57,697 basehttp 124 "GET /sms_codes HTTP/1.1" 404 2149
WARNING 2018-11-15 16:27:36,459 base 152 Not Found: /
WARNING 2018-11-15 16:27:36,466 basehttp 124 "GET / HTTP/1.1" 404 2104
ERROR 2018-11-15 16:41:35,131 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 26, in get
    send_flag=redis_conn.get('smsflag_%s'%mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 16:41:35,335 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152869
ERROR 2018-11-15 16:42:50,575 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 26, in get
    send_flag=redis_conn.get('smsflag_%s'%mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 16:42:50,716 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152870
ERROR 2018-11-15 16:59:01,101 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 16:59:01,349 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152783
ERROR 2018-11-15 17:06:42,408 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 17:06:42,712 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152783
ERROR 2018-11-15 17:11:56,877 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 17:11:57,042 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152783
ERROR 2018-11-15 17:18:29,674 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 17:18:29,853 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152783
ERROR 2018-11-15 17:20:39,562 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 17:20:39,696 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152784
ERROR 2018-11-15 17:29:59,241 exception 135 Internal Server Error: /sms_codes/15812341234/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/verifications/views.py", line 29, in get
    send_flag=redis_conn.get('smsflag_%s'% mobile)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 10.211.55.5:6379. Operation timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 452, in handle_exception
    response = exception_handler(exc, context)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/utils/exceptions.py", line 27, in exception_handler
    if isinstance(exc, DatabaseError) or isinstance(RedisError):
TypeError: isinstance expected 2 arguments, got 1
ERROR 2018-11-15 17:29:59,437 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 500 152811
ERROR 2018-11-15 17:34:31,091 basehttp 124 "GET /sms_codes/15812341234/ HTTP/1.1" 507 30
INFO 2018-11-15 17:41:04,869 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-15 18:25:42,315 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-15 18:27:11,006 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-15 19:27:25,026 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-15 19:27:25,233 tasks 22 发送验证码短信[失败][ mobile: 15812341235 ]
INFO 2018-11-15 19:59:25,920 basehttp 124 "GET /usernames/testuser1/count/ HTTP/1.1" 200 34
INFO 2018-11-15 20:01:49,184 basehttp 124 "GET /usernames/user1/count/ HTTP/1.1" 200 30
INFO 2018-11-15 20:05:58,238 basehttp 124 "GET /mobiles/15812341235/count/ HTTP/1.1" 200 34
INFO 2018-11-15 20:06:08,366 basehttp 124 "GET /mobiles/15812341234/count/ HTTP/1.1" 200 34
WARNING 2018-11-15 20:06:19,665 base 152 Not Found: /mobiles/1581234124/count/
WARNING 2018-11-15 20:06:19,669 basehttp 124 "GET /mobiles/1581234124/count/ HTTP/1.1" 404 2586
INFO 2018-11-15 20:06:25,673 basehttp 124 "GET /mobiles/15812341224/count/ HTTP/1.1" 200 34
INFO 2018-11-15 20:49:28,884 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-15 20:49:29,142 tasks 22 发送验证码短信[失败][ mobile: 15812341235 ]
WARNING 2018-11-15 20:50:09,216 base 152 Not Found: /register.html
WARNING 2018-11-15 20:50:09,220 basehttp 124 "GET /register.html HTTP/1.1" 404 2710
WARNING 2018-11-15 20:50:10,176 base 152 Not Found: /favicon.ico
WARNING 2018-11-15 20:50:10,177 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2704
WARNING 2018-11-15 20:55:26,735 base 152 Not Found: /register.html
WARNING 2018-11-15 20:55:26,737 basehttp 124 "GET /register.html HTTP/1.1" 404 2710
WARNING 2018-11-15 20:56:42,317 base 152 Not Found: /register.html
WARNING 2018-11-15 20:56:42,321 basehttp 124 "GET /register.html HTTP/1.1" 404 2710
WARNING 2018-11-15 21:15:01,648 base 152 Not Found: /register.html
WARNING 2018-11-15 21:15:01,659 basehttp 124 "GET /register.html HTTP/1.1" 404 2710
INFO 2018-11-15 21:15:31,685 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-15 21:15:46,140 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-15 21:18:10,662 base 152 Not Found: /register.html
WARNING 2018-11-15 21:18:10,664 basehttp 124 "GET /register.html HTTP/1.1" 404 2710
INFO 2018-11-15 21:34:22,837 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-15 21:42:57,067 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-15 21:43:18,157 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-15 21:43:37,655 basehttp 124 "GET /usernames/user1/count/ HTTP/1.1" 200 30
WARNING 2018-11-15 21:43:42,054 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-15 21:47:37,548 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 14:53:18,269 base 152 Not Found: /
WARNING 2018-11-17 14:53:18,273 basehttp 124 "GET / HTTP/1.1" 404 2649
WARNING 2018-11-17 14:53:18,780 base 152 Not Found: /favicon.ico
WARNING 2018-11-17 14:53:18,781 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2700
INFO 2018-11-17 15:06:03,666 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-17 16:01:59,442 basehttp 124 "GET /usernames/user1/count/ HTTP/1.1" 200 30
INFO 2018-11-17 16:02:09,858 basehttp 124 "GET /mobiles/15812341224/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:03:44,837 basehttp 124 "GET /mobiles/15812341235/count/ HTTP/1.1" 200 34
WARNING 2018-11-17 16:04:05,478 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:04:14,777 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
INFO 2018-11-17 16:07:31,537 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:07:45,017 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:09:25,886 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:09:42,313 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 16:10:41,558 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:10:48,280 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:10:59,521 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:18:26,168 basehttp 124 "GET /mobiles/15812341235/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:18:26,241 basehttp 124 "GET /mobiles/15812341235/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:19:43,726 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:20:39,363 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:21:17,125 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
INFO 2018-11-17 16:21:17,150 basehttp 124 "GET /usernames/user1/count/ HTTP/1.1" 200 30
INFO 2018-11-17 16:21:17,150 basehttp 124 "GET /mobiles/15812341235/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:21:17,367 basehttp 124 "POST /users/ HTTP/1.1" 201 50
INFO 2018-11-17 16:21:39,481 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-11-17 16:21:39,491 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:39,492 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:21:41,980 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:41,981 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:21:49,798 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:49,798 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:21:50,679 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:50,679 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:21:58,087 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:58,087 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:21:59,917 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:21:59,917 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
WARNING 2018-11-17 16:22:06,074 base 152 Not Found: /authorizations/
WARNING 2018-11-17 16:22:06,075 basehttp 124 "POST /authorizations/ HTTP/1.1" 404 2717
INFO 2018-11-17 16:37:09,892 basehttp 124 "GET /sms_codes/15812341235/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:37:25,244 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:38:25,963 basehttp 124 "GET /sms_codes/15812341236/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:38:42,213 basehttp 124 "POST /users/ HTTP/1.1" 400 109
INFO 2018-11-17 16:47:38,814 basehttp 124 "GET /usernames/user3/count/ HTTP/1.1" 200 30
INFO 2018-11-17 16:47:53,575 basehttp 124 "GET /mobiles/15812341239/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:47:53,587 basehttp 124 "GET /mobiles/15812341239/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:47:53,769 basehttp 124 "GET /sms_codes/15812341239/ HTTP/1.1" 200 16
INFO 2018-11-17 16:48:07,954 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
INFO 2018-11-17 16:48:07,982 basehttp 124 "GET /mobiles/15812341239/count/ HTTP/1.1" 200 34
INFO 2018-11-17 16:48:07,984 basehttp 124 "GET /usernames/user3/count/ HTTP/1.1" 200 30
INFO 2018-11-17 16:48:08,125 basehttp 124 "POST /users/ HTTP/1.1" 201 50
INFO 2018-11-17 16:49:12,279 basehttp 124 "GET /sms_codes/15812341239/ HTTP/1.1" 200 16
WARNING 2018-11-17 16:49:28,391 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 16:50:56,602 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 16:53:12,649 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 16:54:15,704 basehttp 124 "POST /users/ HTTP/1.1" 400 113
WARNING 2018-11-17 16:54:30,822 basehttp 124 "POST /users/ HTTP/1.1" 400 109
WARNING 2018-11-17 16:54:37,236 basehttp 124 "POST /users/ HTTP/1.1" 400 113
INFO 2018-11-17 17:25:17,133 basehttp 124 "GET /sms_codes/15812341240/ HTTP/1.1" 200 16
INFO 2018-11-17 17:25:35,285 basehttp 124 "POST /users/ HTTP/1.1" 201 222
WARNING 2018-11-17 17:32:25,443 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 108
WARNING 2018-11-17 17:32:32,837 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-11-17 19:05:18,912 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 210
INFO 2018-11-17 19:05:50,561 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-11-17 19:06:32,700 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2018-11-17 19:16:23,168 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-17 19:17:51,369 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-17 19:20:07,021 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-11-17 19:20:21,415 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
WARNING 2018-11-17 19:20:36,563 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
INFO 2018-11-17 19:20:43,003 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-11-17 19:49:37,197 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-11-17 19:49:46,823 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-11-17 20:50:06,770 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:03:49,298 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:03:54,579 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:04,476 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:05,216 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:07,283 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:10,347 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:10,722 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:10,890 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:11,080 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:11,274 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:11,491 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 17:04:13,096 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 18:33:32,197 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 18:33:48,745 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 18:33:53,244 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 19:36:31,096 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 19:41:28,714 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-18 19:41:52,674 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:28:51,375 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:33:26,431 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:41:26,879 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:41:37,075 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:41:38,963 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:41:40,087 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:42:24,363 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:43:40,410 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:50:28,753 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 16:50:44,493 basehttp 124 "GET /oauth/qq/user/?code=41596B36114ECBEAE3D95EB813789850 HTTP/1.1" 200 233
ERROR 2018-11-20 16:50:58,881 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/oauth/views.py", line 64, in get
    access_token = oauth.get_access_token(code)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/QQLoginTool/QQtool.py", line 63, in get_access_token
    raise Exception('access_token获取失败')
Exception: access_token获取失败
ERROR 2018-11-20 16:50:58,998 basehttp 124 "GET /oauth/qq/user/?code=41596B36114ECBEAE3D95EB813789850 HTTP/1.1" 500 16860
ERROR 2018-11-20 16:50:59,902 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/oauth/views.py", line 64, in get
    access_token = oauth.get_access_token(code)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/QQLoginTool/QQtool.py", line 63, in get_access_token
    raise Exception('access_token获取失败')
Exception: access_token获取失败
ERROR 2018-11-20 16:50:59,930 basehttp 124 "GET /oauth/qq/user/?code=41596B36114ECBEAE3D95EB813789850 HTTP/1.1" 500 16860
INFO 2018-11-20 16:52:50,217 basehttp 124 "GET /oauth/qq/user/?code=F7F509C45BC997581446BC806781F326 HTTP/1.1" 200 233
INFO 2018-11-20 16:53:02,317 basehttp 124 "GET /oauth/qq/user/?code=12F672C4ED328C6A2F1E89437C7F6E98 HTTP/1.1" 200 233
ERROR 2018-11-20 16:53:40,781 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/oauth/views.py", line 64, in get
    access_token = oauth.get_access_token(code)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/QQLoginTool/QQtool.py", line 63, in get_access_token
    raise Exception('access_token获取失败')
Exception: access_token获取失败
ERROR 2018-11-20 16:53:40,964 basehttp 124 "GET /oauth/qq/user/?code=12F672C4ED328C6A2F1E89437C7F6E98 HTTP/1.1" 500 16860
INFO 2018-11-20 16:58:38,928 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
ERROR 2018-11-20 16:59:46,508 exception 135 Internal Server Error: /oauth/qq/user/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/oauth/views.py", line 64, in get
    access_token = oauth.get_access_token(code)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/QQLoginTool/QQtool.py", line 63, in get_access_token
    raise Exception('access_token获取失败')
Exception: access_token获取失败
ERROR 2018-11-20 16:59:46,673 basehttp 124 "GET /oauth/qq/user/?code=9B9CA63529C97D7083313D1D2CDF15D9 HTTP/1.1" 500 16852
INFO 2018-11-20 17:03:02,538 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 17:03:07,810 basehttp 124 "GET /oauth/qq/user/?code=E35DBEBF5E21894C0E8FA47514EDE874 HTTP/1.1" 200 233
INFO 2018-11-20 17:03:18,631 basehttp 124 "GET /sms_codes/15812341240/ HTTP/1.1" 200 16
INFO 2018-11-20 17:03:41,301 basehttp 124 "OPTIONS /oauth/qq/user/ HTTP/1.1" 200 0
INFO 2018-11-20 17:03:41,481 basehttp 124 "POST /oauth/qq/user/ HTTP/1.1" 200 204
INFO 2018-11-20 17:08:19,387 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 173
INFO 2018-11-20 17:10:25,733 basehttp 124 "GET /oauth/qq/authorization/?next=/ HTTP/1.1" 200 175
INFO 2018-11-20 17:10:37,538 basehttp 124 "GET /oauth/qq/user/?code=BD13E2608CD492B18FA04D20D240104F HTTP/1.1" 200 204
INFO 2018-11-20 18:59:41,219 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-20 18:59:41,456 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 204
INFO 2018-11-20 19:01:19,188 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-20 19:01:19,298 basehttp 124 "GET /user/ HTTP/1.1" 200 82
INFO 2018-11-20 19:01:19,412 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-20 19:01:19,459 base 152 Not Found: /browse_histories/
WARNING 2018-11-20 19:01:19,460 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3151
INFO 2018-11-20 20:10:16,662 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-20 20:10:17,506 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-20 20:22:11,840 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-20 20:22:12,037 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 226
INFO 2018-11-20 20:22:12,219 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-20 20:22:12,279 basehttp 124 "GET /user/ HTTP/1.1" 200 98
INFO 2018-11-20 20:22:12,412 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-20 20:22:12,474 base 152 Not Found: /browse_histories/
WARNING 2018-11-20 20:22:12,475 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3307
INFO 2018-11-20 20:22:16,476 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-20 20:22:17,039 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
WARNING 2018-11-20 20:22:29,871 base 152 Not Found: /emails/verification/
WARNING 2018-11-20 20:22:29,873 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0MjcxNjUzNiwiZXhwIjoxNTQyNzIwMTM2fQ.eyJ1c2VyX2lkIjozLCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.sE2ACqCqn3pb8FnFmEzptE9_s301Wv1jeML2MNG1WVWUeI9GYN69zbumTM6mJo1FNvvyuvpao_0_BD4t4sHNlg HTTP/1.1" 404 3531
WARNING 2018-11-20 20:22:38,302 base 152 Not Found: /emails/verification/
WARNING 2018-11-20 20:22:38,303 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0MjcxNjUzNiwiZXhwIjoxNTQyNzIwMTM2fQ.eyJ1c2VyX2lkIjozLCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.sE2ACqCqn3pb8FnFmEzptE9_s301Wv1jeML2MNG1WVWUeI9GYN69zbumTM6mJo1FNvvyuvpao_0_BD4t4sHNlg HTTP/1.1" 404 3531
INFO 2018-11-20 20:40:28,093 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-20 20:40:28,355 basehttp 124 "GET /user/ HTTP/1.1" 200 98
INFO 2018-11-20 20:40:28,436 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-20 20:40:28,488 base 152 Not Found: /browse_histories/
WARNING 2018-11-20 20:40:28,490 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-20 20:40:30,421 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-20 20:40:30,991 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-20 20:40:41,649 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0MjcxNzYzMCwiZXhwIjoxNTQyNzIxMjMwfQ.eyJ1c2VyX2lkIjozLCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.EqCOP5tzj7FLUGTNzmVtHBuN-o5WAxuqjLbm6SZAOp6gHgxatcQMAkbp4BPltBp9qY7utOKCCmvRQLvoHA7iYQ HTTP/1.1" 200 16
INFO 2018-11-20 20:41:18,922 basehttp 124 "GET /user/ HTTP/1.1" 200 97
WARNING 2018-11-20 20:41:18,980 base 152 Not Found: /browse_histories/
WARNING 2018-11-20 20:41:18,981 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 00:20:06,711 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-11-22 00:20:06,904 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
WARNING 2018-11-22 00:20:27,483 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
WARNING 2018-11-22 00:20:54,149 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
WARNING 2018-11-22 00:21:01,271 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-22 00:22:00,566 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-22 00:22:01,334 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-22 00:22:03,530 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 67
WARNING 2018-11-22 00:22:14,540 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
INFO 2018-11-22 00:23:20,056 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
WARNING 2018-11-22 00:23:20,246 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
WARNING 2018-11-22 00:23:42,991 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
INFO 2018-11-22 00:23:48,989 basehttp 124 "GET /usernames/15812341222/count/ HTTP/1.1" 200 36
INFO 2018-11-22 00:24:00,202 basehttp 124 "GET /mobiles/15812341222/count/ HTTP/1.1" 200 34
INFO 2018-11-22 00:24:00,215 basehttp 124 "GET /mobiles/15812341222/count/ HTTP/1.1" 200 34
INFO 2018-11-22 00:24:00,433 basehttp 124 "GET /sms_codes/15812341222/ HTTP/1.1" 200 16
INFO 2018-11-22 00:24:29,056 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
INFO 2018-11-22 00:24:29,080 basehttp 124 "GET /mobiles/15812341222/count/ HTTP/1.1" 200 34
INFO 2018-11-22 00:24:29,080 basehttp 124 "GET /usernames/15812341222/count/ HTTP/1.1" 200 36
INFO 2018-11-22 00:24:29,188 basehttp 124 "POST /users/ HTTP/1.1" 201 236
INFO 2018-11-22 00:24:32,397 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-22 00:24:32,486 basehttp 124 "GET /user/ HTTP/1.1" 200 88
INFO 2018-11-22 00:24:32,535 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-22 00:24:32,570 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 00:24:32,571 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 00:24:39,617 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-22 00:24:40,897 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-22 00:24:41,773 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
WARNING 2018-11-22 00:26:39,636 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 49
INFO 2018-11-22 00:27:00,865 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-22 16:50:23,086 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-22 16:50:23,316 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-22 16:50:25,396 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-22 16:50:25,541 basehttp 124 "GET /user/ HTTP/1.1" 200 104
INFO 2018-11-22 16:50:25,675 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-22 16:50:25,747 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 16:50:25,748 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 16:50:29,221 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-22 16:50:30,493 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-22 16:50:44,134 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0Mjg3NjYyOSwiZXhwIjoxNTQyODgwMjI5fQ.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.BXObC6AwCZQZBxVB7nL9upozQQltW0DCalC2_vXkK_RKoJTKycZrX7qlA4qUabod51z6qPcOa5fd3rdazz-nIA HTTP/1.1" 200 16
INFO 2018-11-22 16:50:55,268 basehttp 124 "GET /user/ HTTP/1.1" 200 103
WARNING 2018-11-22 16:50:55,308 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 16:50:55,309 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 17:11:46,036 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-22 17:11:46,239 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-22 17:11:48,814 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-22 17:11:48,884 basehttp 124 "GET /user/ HTTP/1.1" 200 103
INFO 2018-11-22 17:11:48,943 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-22 17:11:48,986 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 17:11:48,987 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 17:12:07,161 basehttp 124 "GET /user/ HTTP/1.1" 200 104
WARNING 2018-11-22 17:12:07,189 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 17:12:07,191 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
WARNING 2018-11-22 17:15:24,283 tasks 22 发送验证码短信[失败][ mobile: 15812341222 ]
INFO 2018-11-22 17:16:15,453 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
ERROR 2018-11-22 17:16:15,742 exception 135 Internal Server Error: /email/
Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yinshuanglong/Desktop/mido/mido_mall/mido_mall/apps/users/views.py", line 142, in put
    send_email.delay(user)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/celery/app/task.py", line 408, in delay
    return self.apply_async(args, kwargs)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/celery/app/base.py", line 745, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/vine/five.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/yinshuanglong/dj/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
kombu.exceptions.EncodeError: Object of type 'User' is not JSON serializable
ERROR 2018-11-22 17:16:15,896 basehttp 124 "PUT /email/ HTTP/1.1" 500 20697
INFO 2018-11-22 17:20:45,820 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-22 21:07:36,685 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-22 21:07:36,906 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-22 21:07:39,873 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-22 21:07:39,990 basehttp 124 "GET /user/ HTTP/1.1" 200 104
INFO 2018-11-22 21:07:40,065 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-22 21:07:40,143 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 21:07:40,144 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-22 21:07:41,433 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-22 21:07:41,701 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-22 21:07:51,535 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0Mjg5MjA2MSwiZXhwIjoxNTQyODk1NjYxfQ.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.WaZnX6LZGtMNyF1pyd8yjMLzOOkdwCZfJ-y6MGV-D97yuu7c0AZBTo5Sci9YcEtOR1EPAK-rQJGbp99Vospppw HTTP/1.1" 200 16
INFO 2018-11-22 21:07:59,062 basehttp 124 "GET /user/ HTTP/1.1" 200 103
WARNING 2018-11-22 21:07:59,114 base 152 Not Found: /browse_histories/
WARNING 2018-11-22 21:07:59,115 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-23 15:57:10,716 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-23 15:57:10,930 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-23 15:57:13,777 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-23 15:57:13,895 basehttp 124 "GET /user/ HTTP/1.1" 200 104
INFO 2018-11-23 15:57:14,001 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-23 15:57:14,076 base 152 Not Found: /browse_histories/
WARNING 2018-11-23 15:57:14,077 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-23 15:57:31,276 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-23 15:57:31,591 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-23 16:15:29,384 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-23 16:15:29,582 basehttp 124 "GET /user/ HTTP/1.1" 200 104
INFO 2018-11-23 16:15:29,660 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-23 16:15:29,720 base 152 Not Found: /browse_histories/
WARNING 2018-11-23 16:15:29,722 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 3477
INFO 2018-11-23 16:15:30,585 basehttp 124 "OPTIONS /email/ HTTP/1.1" 200 0
INFO 2018-11-23 16:15:30,841 basehttp 124 "PUT /email/ HTTP/1.1" 200 16
INFO 2018-11-23 16:15:48,487 basehttp 124 "GET /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU0Mjk2MDkzMCwiZXhwIjoxNTQyOTY0NTMwfQ.eyJ1c2VyX2lkIjo1LCJlbWFpbCI6Ijg3MTY5Mjc0NkBxcS5jb20ifQ.p2CoJiXHUs2fNhAIOjWyEH01WsDRcV7fA9oHsoroKrE7SQO4nmpo8-_aKnr34T-YfWUusBcRcuCVByOVLNHdXw HTTP/1.1" 200 16
INFO 2018-11-23 19:36:20,629 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
WARNING 2018-11-23 19:36:20,690 base 152 Not Found: /addresses/
WARNING 2018-11-23 19:36:20,691 basehttp 124 "GET /addresses/ HTTP/1.1" 404 3829
INFO 2018-11-23 19:36:20,739 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 19:36:28,674 basehttp 124 "GET /areas/310000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:36:30,494 basehttp 124 "GET /areas/310100/ HTTP/1.1" 200 74
WARNING 2018-11-23 19:39:49,011 base 152 Not Found: /addresses/
WARNING 2018-11-23 19:39:49,015 basehttp 124 "GET /addresses/ HTTP/1.1" 404 3829
INFO 2018-11-23 19:39:49,029 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 19:39:54,470 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:39:58,477 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 19:40:01,935 basehttp 124 "GET /areas/140000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:40:06,596 basehttp 124 "GET /areas/150000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:40:14,505 basehttp 124 "GET /areas/330000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:40:22,495 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
WARNING 2018-11-23 19:40:22,501 base 152 Not Found: /addresses/
WARNING 2018-11-23 19:40:22,502 basehttp 124 "GET /addresses/ HTTP/1.1" 404 3829
INFO 2018-11-23 19:40:25,463 basehttp 124 "GET /areas/320000/ HTTP/1.1" 200 74
INFO 2018-11-23 19:40:27,170 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:13:02,725 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-11-23 20:13:02,871 basehttp 124 "GET /addresses/ HTTP/1.1" 200 50
INFO 2018-11-23 20:13:02,896 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 20:13:10,685 basehttp 124 "GET /areas/310000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:13:12,255 basehttp 124 "GET /areas/310100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:13:42,815 basehttp 124 "POST /addresses/ HTTP/1.1" 200 165
INFO 2018-11-23 20:13:48,979 basehttp 124 "OPTIONS /addresses/1/status/ HTTP/1.1" 200 0
INFO 2018-11-23 20:13:49,022 basehttp 124 "PUT /addresses/1/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:14:10,345 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:14:11,933 basehttp 124 "GET /areas/310100/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:19,194 basehttp 124 "GET /areas/310000/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:31,041 basehttp 124 "GET /areas/310104/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:31,917 basehttp 124 "OPTIONS /addresses/1/ HTTP/1.1" 200 0
INFO 2018-11-23 20:14:31,957 basehttp 124 "PUT /addresses/1/ HTTP/1.1" 200 165
INFO 2018-11-23 20:14:41,579 basehttp 124 "GET /areas/310000/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:43,956 basehttp 124 "GET /areas/310105/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:45,870 basehttp 124 "GET /areas/310107/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:50,136 basehttp 124 "GET /areas/110000/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:52,438 basehttp 124 "GET /areas/310104/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:54,343 basehttp 124 "GET /areas/310109/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:56,264 basehttp 124 "GET /areas/310113/ HTTP/1.1" 200 572
INFO 2018-11-23 20:14:58,124 basehttp 124 "GET /areas/310115/ HTTP/1.1" 200 572
INFO 2018-11-23 20:15:01,402 basehttp 124 "GET /areas/310114/ HTTP/1.1" 200 572
INFO 2018-11-23 20:15:02,997 basehttp 124 "GET /areas/310110/ HTTP/1.1" 200 572
INFO 2018-11-23 20:15:09,863 basehttp 124 "GET /areas/110000/ HTTP/1.1" 200 572
INFO 2018-11-23 20:15:17,902 basehttp 124 "GET /areas/310104/ HTTP/1.1" 200 42
INFO 2018-11-23 20:19:06,158 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:19:07,474 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
WARNING 2018-11-23 20:19:13,006 basehttp 124 "POST /addresses/ HTTP/1.1" 400 39
WARNING 2018-11-23 20:19:14,232 basehttp 124 "POST /addresses/ HTTP/1.1" 400 39
WARNING 2018-11-23 20:19:16,290 basehttp 124 "POST /addresses/ HTTP/1.1" 400 39
INFO 2018-11-23 20:20:59,016 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:21:00,599 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:21:02,630 basehttp 124 "PUT /addresses/1/ HTTP/1.1" 200 166
INFO 2018-11-23 20:21:12,859 basehttp 124 "GET /areas/320000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:21:14,630 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:21:30,750 basehttp 124 "POST /addresses/ HTTP/1.1" 200 174
INFO 2018-11-23 20:21:43,502 basehttp 124 "OPTIONS /addresses/2/status/ HTTP/1.1" 200 0
INFO 2018-11-23 20:21:43,562 basehttp 124 "PUT /addresses/2/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:21:45,418 basehttp 124 "PUT /addresses/1/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:24:57,956 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:24:59,246 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:28:07,217 basehttp 124 "PUT /addresses/2/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:28:11,866 basehttp 124 "GET /areas/130000/ HTTP/1.1" 200 464
INFO 2018-11-23 20:28:13,664 basehttp 124 "GET /areas/130200/ HTTP/1.1" 200 464
INFO 2018-11-23 20:28:17,823 basehttp 124 "GET /areas/130400/ HTTP/1.1" 200 464
INFO 2018-11-23 20:28:24,063 basehttp 124 "GET /areas/320000/ HTTP/1.1" 200 464
INFO 2018-11-23 20:30:17,843 basehttp 124 "OPTIONS /authorizations/ HTTP/1.1" 200 0
INFO 2018-11-23 20:30:17,954 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 240
INFO 2018-11-23 20:30:19,762 basehttp 124 "OPTIONS /user/ HTTP/1.1" 200 0
INFO 2018-11-23 20:30:19,807 basehttp 124 "GET /user/ HTTP/1.1" 200 103
INFO 2018-11-23 20:30:19,904 basehttp 124 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2018-11-23 20:30:19,976 base 152 Not Found: /browse_histories/
WARNING 2018-11-23 20:30:19,978 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4655
INFO 2018-11-23 20:30:22,477 basehttp 124 "OPTIONS /addresses/ HTTP/1.1" 200 0
INFO 2018-11-23 20:30:22,586 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 20:30:22,622 basehttp 124 "GET /addresses/ HTTP/1.1" 200 391
INFO 2018-11-23 20:30:28,841 basehttp 124 "GET /areas/120000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:30:30,164 basehttp 124 "GET /areas/120100/ HTTP/1.1" 200 74
INFO 2018-11-23 20:30:38,829 basehttp 124 "GET /areas/350000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:30:43,585 basehttp 124 "OPTIONS /addresses/1/status/ HTTP/1.1" 200 0
INFO 2018-11-23 20:30:43,642 basehttp 124 "PUT /addresses/1/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:30:48,046 basehttp 124 "GET /areas/500000/ HTTP/1.1" 200 74
INFO 2018-11-23 20:36:13,815 basehttp 124 "GET /user/ HTTP/1.1" 200 103
WARNING 2018-11-23 20:36:13,858 base 152 Not Found: /browse_histories/
WARNING 2018-11-23 20:36:13,859 basehttp 124 "GET /browse_histories/ HTTP/1.1" 404 4655
INFO 2018-11-23 20:36:27,807 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 20:36:27,834 basehttp 124 "GET /addresses/ HTTP/1.1" 200 391
INFO 2018-11-23 20:36:32,123 basehttp 124 "GET /areas/ HTTP/1.1" 200 1204
INFO 2018-11-23 20:36:32,154 basehttp 124 "GET /addresses/ HTTP/1.1" 200 391
INFO 2018-11-23 20:36:37,144 basehttp 124 "OPTIONS /addresses/2/status/ HTTP/1.1" 200 0
INFO 2018-11-23 20:36:37,249 basehttp 124 "PUT /addresses/2/status/ HTTP/1.1" 200 16
INFO 2018-11-23 20:36:40,931 basehttp 124 "GET /areas/140000/ HTTP/1.1" 200 404
INFO 2018-11-23 20:36:43,345 basehttp 124 "GET /areas/140200/ HTTP/1.1" 200 404
INFO 2018-11-23 20:36:50,297 basehttp 124 "GET /areas/140500/ HTTP/1.1" 200 404
INFO 2018-11-23 20:44:26,672 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-23 20:44:26,726 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-23 20:44:26,732 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-23 20:44:26,737 base 152 Not Found: /categories/115/
WARNING 2018-11-23 20:44:26,741 base 152 Not Found: /cart/
WARNING 2018-11-23 20:44:26,743 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-23 20:44:26,744 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4649
WARNING 2018-11-23 20:44:26,744 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-23 20:44:26,746 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-23 20:44:28,377 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-23 20:44:28,378 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 404 4706
INFO 2018-11-25 10:01:58,747 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 10:01:59,052 base 152 Not Found: /cart/
WARNING 2018-11-25 10:01:59,063 base 152 Not Found: /categories/115/
WARNING 2018-11-25 10:01:59,064 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:01:59,064 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:01:59,067 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:01:59,082 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:01:59,090 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 10:01:59,117 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:02:03,268 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:02:03,269 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 404 4706
WARNING 2018-11-25 10:02:05,195 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:02:05,199 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 404 4706
WARNING 2018-11-25 10:02:06,177 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:02:06,177 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:02:07,725 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:02:07,731 base 152 Not Found: /categories/115/
WARNING 2018-11-25 10:02:07,733 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:02:07,734 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:02:07,748 base 152 Not Found: /cart/
WARNING 2018-11-25 10:02:07,756 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 10:02:07,757 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:02:07,759 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:05:08,681 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 10:05:08,683 base 152 Not Found: /categories/115/skus/
WARNING 2018-11-25 10:05:08,685 base 152 Not Found: /cart/
WARNING 2018-11-25 10:05:08,697 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:05:08,692 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:05:08,695 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:05:08,691 base 152 Not Found: /categories/115/
WARNING 2018-11-25 10:05:08,702 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4649
INFO 2018-11-25 10:23:27,275 basehttp 124 "GET /admin HTTP/1.1" 301 0
INFO 2018-11-25 10:23:27,377 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2018-11-25 10:23:27,525 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
INFO 2018-11-25 10:23:27,591 basehttp 124 "GET /static/admin/css/base.css HTTP/1.1" 200 16066
INFO 2018-11-25 10:23:27,592 basehttp 124 "GET /static/admin/css/login.css HTTP/1.1" 200 1203
INFO 2018-11-25 10:23:27,699 basehttp 124 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2018-11-25 10:23:27,830 basehttp 124 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
INFO 2018-11-25 10:23:27,857 basehttp 124 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
WARNING 2018-11-25 10:23:28,178 base 152 Not Found: /favicon.ico
WARNING 2018-11-25 10:23:28,180 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 4631
INFO 2018-11-25 10:23:30,496 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1784
INFO 2018-11-25 10:23:30,646 basehttp 124 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
INFO 2018-11-25 10:23:40,098 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1784
INFO 2018-11-25 10:25:08,972 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2018-11-25 10:25:09,082 basehttp 124 "GET /admin/ HTTP/1.1" 200 3479
INFO 2018-11-25 10:25:09,168 basehttp 124 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2018-11-25 10:25:09,315 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2018-11-25 10:25:09,315 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2018-11-25 10:27:45,792 basehttp 124 "GET /admin/contents/contentcategory/ HTTP/1.1" 200 8617
INFO 2018-11-25 10:27:45,891 basehttp 124 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
INFO 2018-11-25 10:27:45,897 basehttp 124 "GET /static/admin/js/core.js HTTP/1.1" 200 7976
INFO 2018-11-25 10:27:45,907 basehttp 124 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
INFO 2018-11-25 10:27:45,936 basehttp 124 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
INFO 2018-11-25 10:27:45,936 basehttp 124 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO 2018-11-25 10:27:45,936 basehttp 124 "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
INFO 2018-11-25 10:27:45,937 basehttp 124 "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
INFO 2018-11-25 10:27:45,945 basehttp 124 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
INFO 2018-11-25 10:27:45,955 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:27:45,961 basehttp 124 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
INFO 2018-11-25 10:27:46,133 basehttp 124 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2018-11-25 10:28:01,107 basehttp 124 "GET /admin/contents/contentcategory/25/change/ HTTP/1.1" 200 4672
INFO 2018-11-25 10:28:01,150 basehttp 124 "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
INFO 2018-11-25 10:28:01,167 basehttp 124 "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2018-11-25 10:28:01,168 basehttp 124 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2018-11-25 10:28:01,184 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:28:01,228 basehttp 124 "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2018-11-25 10:28:09,673 basehttp 124 "POST /admin/contents/contentcategory/25/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:28:09,733 basehttp 124 "GET /admin/contents/contentcategory/25/change/ HTTP/1.1" 200 4916
INFO 2018-11-25 10:28:09,783 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:28:09,872 basehttp 124 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2018-11-25 10:31:10,109 basehttp 124 "POST /admin/contents/contentcategory/25/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:31:10,372 basehttp 124 "GET /admin/contents/contentcategory/25/change/ HTTP/1.1" 200 4910
INFO 2018-11-25 10:31:10,456 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:31:13,424 basehttp 124 "GET /admin/contents/ HTTP/1.1" 200 2691
INFO 2018-11-25 10:31:15,770 basehttp 124 "GET /admin/contents/ HTTP/1.1" 200 2691
INFO 2018-11-25 10:31:17,353 basehttp 124 "GET /admin/ HTTP/1.1" 200 8189
INFO 2018-11-25 10:31:19,233 basehttp 124 "GET /admin/ HTTP/1.1" 200 8189
INFO 2018-11-25 10:31:36,909 basehttp 124 "GET /admin/goods/skuimage/ HTTP/1.1" 200 15619
INFO 2018-11-25 10:31:36,992 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:31:41,074 basehttp 124 "GET /admin/goods/skuimage/43/change/ HTTP/1.1" 200 7073
INFO 2018-11-25 10:31:41,136 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:31:46,886 basehttp 124 "GET /admin/goods/skuimage/ HTTP/1.1" 200 15619
INFO 2018-11-25 10:31:48,088 basehttp 124 "GET /admin/ HTTP/1.1" 200 8189
INFO 2018-11-25 10:35:13,571 basehttp 124 "GET /admin/goods/goodscategory/ HTTP/1.1" 200 27852
INFO 2018-11-25 10:35:13,663 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:35:15,672 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 27986
INFO 2018-11-25 10:35:15,754 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:35:20,146 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:35:20,437 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28218
INFO 2018-11-25 10:35:20,549 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:35:31,035 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:35:31,340 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28210
INFO 2018-11-25 10:35:31,406 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:40:34,699 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:40:35,015 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28218
INFO 2018-11-25 10:40:35,169 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:41:07,501 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:41:07,792 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28210
INFO 2018-11-25 10:41:07,906 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:41:09,945 basehttp 124 "GET /admin/ HTTP/1.1" 200 9425
WARNING 2018-11-25 10:41:21,526 base 152 Not Found: /categories/115/skus/
INFO 2018-11-25 10:41:21,538 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 10:41:21,548 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 10:41:21,555 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:41:21,558 base 152 Not Found: /categories/115/
WARNING 2018-11-25 10:41:21,559 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:41:21,563 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:41:21,601 base 152 Not Found: /cart/
WARNING 2018-11-25 10:41:21,602 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
INFO 2018-11-25 10:42:12,950 basehttp 124 "GET /admin/ HTTP/1.1" 200 9425
INFO 2018-11-25 10:42:18,102 basehttp 124 "GET /admin/goods/brand/ HTTP/1.1" 200 4406
INFO 2018-11-25 10:42:18,186 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:42:21,222 basehttp 124 "GET /admin/goods/ HTTP/1.1" 200 5583
INFO 2018-11-25 10:42:23,201 basehttp 124 "GET /admin/goods/goodscategory/ HTTP/1.1" 200 27852
INFO 2018-11-25 10:42:23,300 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:42:36,580 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 27986
INFO 2018-11-25 10:42:36,652 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 10:42:42,110 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:42:42,374 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28230
INFO 2018-11-25 10:42:42,437 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 10:43:10,206 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:43:10,208 base 152 Not Found: /categories/555/skus/
INFO 2018-11-25 10:43:10,217 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 10:43:10,222 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:43:10,222 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:43:10,223 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:43:10,226 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:43:10,250 base 152 Not Found: /cart/
WARNING 2018-11-25 10:43:10,252 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
INFO 2018-11-25 10:43:39,279 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:43:39,547 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28210
INFO 2018-11-25 10:43:39,680 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 10:43:40,421 base 152 Not Found: /categories/555/skus/
WARNING 2018-11-25 10:43:40,428 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:43:40,435 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:43:40,440 base 152 Not Found: /cart/
WARNING 2018-11-25 10:43:40,447 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:43:40,448 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:43:40,449 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:43:40,450 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
INFO 2018-11-25 10:44:03,313 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:44:03,826 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28230
INFO 2018-11-25 10:44:03,936 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 10:44:04,975 base 152 Not Found: /categories/555/skus/
WARNING 2018-11-25 10:44:04,988 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:44:04,989 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:44:05,007 base 152 Not Found: /cart/
WARNING 2018-11-25 10:44:05,009 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:44:05,018 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:44:05,023 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:44:05,025 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
INFO 2018-11-25 10:44:15,854 basehttp 124 "POST /admin/goods/goodscategory/555/change/ HTTP/1.1" 302 0
INFO 2018-11-25 10:44:16,137 basehttp 124 "GET /admin/goods/goodscategory/555/change/ HTTP/1.1" 200 28210
INFO 2018-11-25 10:44:16,210 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 10:44:16,860 base 152 Not Found: /categories/555/skus/
WARNING 2018-11-25 10:44:16,876 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:44:16,891 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:44:16,901 base 152 Not Found: /cart/
WARNING 2018-11-25 10:44:16,906 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:44:16,906 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:44:16,908 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:44:16,911 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:45:08,149 base 152 Not Found: /categories/555/skus/
WARNING 2018-11-25 10:45:08,158 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:45:08,170 base 152 Not Found: /cart/
WARNING 2018-11-25 10:45:08,170 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
WARNING 2018-11-25 10:45:08,182 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:45:08,182 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:45:08,183 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:45:08,188 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:50:09,074 base 152 Not Found: /categories/555/
WARNING 2018-11-25 10:50:09,078 base 152 Not Found: /categories/555/skus/
WARNING 2018-11-25 10:50:09,088 base 152 Not Found: /cart/
WARNING 2018-11-25 10:50:09,102 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 10:50:09,103 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4649
WARNING 2018-11-25 10:50:09,105 basehttp 124 "GET /cart/ HTTP/1.1" 404 4619
WARNING 2018-11-25 10:50:09,105 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4673
WARNING 2018-11-25 10:50:09,109 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 4713
INFO 2018-11-25 11:08:01,233 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 11:08:01,288 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 11:08:01,291 base 152 Not Found: /categories/555/
WARNING 2018-11-25 11:08:01,292 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4866
WARNING 2018-11-25 11:08:01,293 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4842
INFO 2018-11-25 11:08:01,325 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-11-25 11:08:01,344 base 152 Not Found: /cart/
WARNING 2018-11-25 11:08:01,345 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:08:09,172 base 152 Not Found: /categories/555/
WARNING 2018-11-25 11:08:09,182 base 152 Not Found: /cart/
WARNING 2018-11-25 11:08:09,198 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 11:08:09,200 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:08:09,201 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:08:09,201 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:08:09,211 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-11-25 11:09:11,947 base 152 Not Found: /categories/555/
WARNING 2018-11-25 11:09:11,958 base 152 Not Found: /cart/
WARNING 2018-11-25 11:09:11,960 basehttp 124 "GET /categories/555/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:09:11,963 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:09:11,978 base 152 Not Found: /categories/555/hotskus/
WARNING 2018-11-25 11:09:11,979 basehttp 124 "GET /categories/555/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:09:11,990 basehttp 124 "GET /categories/555/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 52
WARNING 2018-11-25 11:09:19,566 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:09:19,574 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:09:19,578 base 152 Not Found: /cart/
WARNING 2018-11-25 11:09:19,585 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:09:19,587 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:09:19,590 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:09:19,625 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-25 11:09:23,645 basehttp 124 "GET /categories/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1369
INFO 2018-11-25 11:09:25,880 basehttp 124 "GET /categories/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 1033
INFO 2018-11-25 11:09:27,647 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:10:04,369 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:10:04,385 base 152 Not Found: /cart/
WARNING 2018-11-25 11:10:04,400 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:10:04,401 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:10:04,403 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:10:04,407 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:10:04,425 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:10:13,206 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:10:13,219 base 152 Not Found: /cart/
WARNING 2018-11-25 11:10:13,220 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:10:13,229 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:10:13,236 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:10:13,239 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:10:13,253 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-25 11:11:20,111 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-11-25 11:11:21,755 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
INFO 2018-11-25 11:11:23,209 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-11-25 11:11:24,261 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
INFO 2018-11-25 11:11:25,234 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-11-25 11:11:26,207 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-25 11:11:26,977 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=price HTTP/1.1" 200 1312
INFO 2018-11-25 11:11:28,433 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=sales HTTP/1.1" 200 1270
WARNING 2018-11-25 11:15:08,629 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:15:08,645 base 152 Not Found: /cart/
WARNING 2018-11-25 11:15:08,646 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:15:08,648 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:15:08,662 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:15:08,667 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:15:08,689 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:17:56,407 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:17:56,408 base 152 Not Found: /cart/
WARNING 2018-11-25 11:17:56,416 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:17:56,419 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:17:56,419 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:17:56,425 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:17:56,454 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:18:19,936 base 152 Not Found: /categories/115/
INFO 2018-11-25 11:18:19,952 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 11:18:19,953 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:18:19,954 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:18:19,958 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:18:19,976 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:18:20,140 base 152 Not Found: /cart/
WARNING 2018-11-25 11:18:20,141 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:18:22,357 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:18:22,375 base 152 Not Found: /cart/
WARNING 2018-11-25 11:18:22,379 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:18:22,395 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:18:22,395 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:18:22,397 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:18:22,420 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:19:08,744 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:19:08,767 base 152 Not Found: /cart/
WARNING 2018-11-25 11:19:08,783 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:19:08,785 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:19:08,786 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
WARNING 2018-11-25 11:19:08,791 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
INFO 2018-11-25 11:19:08,875 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-25 11:28:59,729 basehttp 124 "GET /admin/ HTTP/1.1" 200 10667
INFO 2018-11-25 11:29:20,477 basehttp 124 "GET /admin/goods/sku/ HTTP/1.1" 200 8576
INFO 2018-11-25 11:29:20,575 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 11:29:22,527 basehttp 124 "GET /admin/goods/sku/16/change/ HTTP/1.1" 200 34196
INFO 2018-11-25 11:29:22,585 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 11:29:22,739 basehttp 124 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2018-11-25 11:29:33,199 basehttp 124 "POST /admin/goods/sku/16/change/ HTTP/1.1" 302 0
INFO 2018-11-25 11:29:33,667 basehttp 124 "GET /admin/goods/sku/16/change/ HTTP/1.1" 200 34486
INFO 2018-11-25 11:29:33,742 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 11:29:35,279 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:29:35,290 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:29:35,292 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:29:35,291 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-25 11:29:35,291 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
INFO 2018-11-25 11:29:35,318 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1323
WARNING 2018-11-25 11:29:35,334 base 152 Not Found: /cart/
WARNING 2018-11-25 11:29:35,335 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
INFO 2018-11-25 11:29:56,485 basehttp 124 "POST /admin/goods/sku/16/change/ HTTP/1.1" 302 0
INFO 2018-11-25 11:29:56,920 basehttp 124 "GET /admin/goods/sku/16/change/ HTTP/1.1" 200 34480
INFO 2018-11-25 11:29:56,999 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
WARNING 2018-11-25 11:29:57,905 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:29:57,917 base 152 Not Found: /cart/
WARNING 2018-11-25 11:29:57,926 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:29:57,940 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:29:57,942 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:29:57,948 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:29:57,972 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-25 11:30:08,585 base 152 Not Found: /categories/115/
WARNING 2018-11-25 11:30:08,592 base 152 Not Found: /cart/
WARNING 2018-11-25 11:30:08,605 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-25 11:30:08,605 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-25 11:30:08,607 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-25 11:30:08,610 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-25 11:30:08,626 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-25 11:32:12,482 basehttp 124 "POST /admin/goods/sku/16/change/ HTTP/1.1" 302 0
INFO 2018-11-25 11:32:12,994 basehttp 124 "GET /admin/goods/sku/16/change/ HTTP/1.1" 200 34486
INFO 2018-11-25 11:32:13,111 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-25 11:32:21,980 basehttp 124 "POST /admin/goods/sku/16/change/ HTTP/1.1" 302 0
INFO 2018-11-25 11:32:22,291 basehttp 124 "GET /admin/goods/sku/16/change/ HTTP/1.1" 200 34480
INFO 2018-11-25 11:32:22,396 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7682
INFO 2018-11-26 10:12:34,389 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-26 10:12:34,430 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:12:34,435 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:12:34,436 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:12:34,437 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
WARNING 2018-11-26 10:12:34,465 base 152 Not Found: /cart/
WARNING 2018-11-26 10:12:34,469 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
INFO 2018-11-26 10:12:34,493 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-26 10:15:07,772 base 152 Not Found: /cart/
WARNING 2018-11-26 10:15:07,781 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:15:07,789 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:15:07,790 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-26 10:15:07,791 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:15:07,791 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-26 10:15:07,807 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-26 10:20:03,841 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:20:03,849 base 152 Not Found: /cart/
WARNING 2018-11-26 10:20:03,857 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:20:03,858 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:20:03,860 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-26 10:20:03,861 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-26 10:20:03,879 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-26 10:25:11,194 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-26 10:25:11,207 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:25:11,208 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:25:11,216 base 152 Not Found: /cart/
WARNING 2018-11-26 10:25:11,218 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:25:11,219 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
WARNING 2018-11-26 10:25:11,225 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
INFO 2018-11-26 10:25:11,264 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-26 10:30:08,043 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:30:08,049 base 152 Not Found: /cart/
WARNING 2018-11-26 10:30:08,056 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:30:08,057 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:30:08,060 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-26 10:30:08,061 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-26 10:30:08,101 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-26 10:35:08,463 base 152 Not Found: /categories/115/
WARNING 2018-11-26 10:35:08,473 base 152 Not Found: /cart/
WARNING 2018-11-26 10:35:08,482 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:35:08,484 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:35:08,484 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
WARNING 2018-11-26 10:35:08,485 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
INFO 2018-11-26 10:35:08,508 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
WARNING 2018-11-26 10:38:11,526 base 152 Not Found: /categories/115/
INFO 2018-11-26 10:38:11,536 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 200 0
WARNING 2018-11-26 10:38:11,538 basehttp 124 "GET /categories/115/ HTTP/1.1" 404 4842
WARNING 2018-11-26 10:38:11,559 base 152 Not Found: /categories/115/hotskus/
WARNING 2018-11-26 10:38:11,563 basehttp 124 "GET /categories/115/hotskus/ HTTP/1.1" 404 4866
WARNING 2018-11-26 10:38:11,615 base 152 Not Found: /cart/
WARNING 2018-11-26 10:38:11,616 basehttp 124 "GET /cart/ HTTP/1.1" 404 4812
INFO 2018-11-26 10:38:11,618 basehttp 124 "GET /categories/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1321
INFO 2018-11-26 18:51:28,573 basehttp 124 "GET /skus/search/?text=%E5%8D%8E HTTP/1.1" 200 1286
INFO 2018-11-26 18:51:48,433 basehttp 124 "GET /skus/search/?text=apple HTTP/1.1" 200 1169
INFO 2018-11-26 18:52:18,829 basehttp 124 "GET /skus/search/?text=apple&page=2 HTTP/1.1" 200 762
INFO 2018-11-26 18:52:38,774 basehttp 124 "GET /skus/search/?text=apple&page=1 HTTP/1.1" 200 1169
